version: '2.1'

services:
  course:
    build: ../microservices/course-service
    image: javatab/course_service:v2
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
    depends_on:
      mongodb:
        condition: service_healthy

  search:
    build: ../microservices/search-service
    image: javatab/search_service:v2
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
    depends_on:
      elasticsearch:
        condition: service_healthy

  student:
    build: ../microservices/student-service
    image: javatab/student_service:v2
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
    depends_on:
      postgres:
        condition: service_healthy

  vote:
    build: ../microservices/vote-service
    image: javatab/vote_service:v2
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
    depends_on:
      redis:
        condition: service_healthy

  course-composite:
    build: ../microservices/course-composite-service
    image: javatab/course_composite_service:v2
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}

  mongodb:
    image: mongo:4.4.2
    mem_limit: 512m
    ports:
      - "27017:27017"
    command: mongod
    healthcheck:
      test: "mongo --eval 'db.stats().ok'"
      interval: 5s
      timeout: 2s
      retries: 60

  postgres:
    image: postgres:13.7-alpine3.16
    mem_limit: 512m
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DATABASE=test
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pwd
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6.2.6-alpine
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 5s
      timeout: 2s
      retries: 60

  elasticsearch:
    image: elasticsearch:7.12.1
    ports:
      - "9300:9300"
      - "9200:9200"
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 60

  eureka:
    build: ../spring-cloud/eureka-server
    image: javatab/eureka:v2
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}

  gateway:
    build: ../spring-cloud/gateway
    image: javatab/gateway:v2
    mem_limit: 512m
    ports:
      - "8443:8443"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
    #depends_on:
    #  auth-server:
    #    condition: service_healthy

  auth-server:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
    build: ../spring-cloud/authorization-server
    image: javatab/auth-server:v2
    mem_limit: 512m
    #healthcheck:
    #  test: "curl --fail --silent http://localhost:9999/actuator/health | grep UP || exit 1"
    #  interval: 5s
    #  timeout: 2s
    #  retries: 60

  config-server:
    build: ../spring-cloud/config-server
    image: javatab/config-server:v2
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker,native
      #- ENCRYPT_KEY=${CONFIG_SERVER_ENCRYPT_KEY}
      - SPRING_SECURITY_USER_NAME=${CONFIG_SERVER_USR}
      - SPRING_SECURITY_USER_PASSWORD=${CONFIG_SERVER_PWD}
    volumes:
      - $PWD/../config-repo:/config-repo